[package]
name = "ws-frame"
version = "0.1.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
edition = "2018"

[lib]
name = "ws_frame"

[features]
default = ["std"]
std = []

[dependencies]
byteorder = "1.3.2"